export interface HytalePermission {
    permission: string;
    command: string;
}
export const HYTALE_PERMISSIONS_DATA: HytalePermission[] = [
    { permission: 'hytale.accesscontrolmodule.command.unban', command: '/unban' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist', command: '/whitelist' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.add', command: '/whitelist add' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.remove', command: '/whitelist remove' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.enable', command: '/whitelist enable' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.disable', command: '/whitelist disable' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.clear', command: '/whitelist clear' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.status', command: '/whitelist status' },
    { permission: 'hytale.accesscontrolmodule.command.whitelist.list', command: '/whitelist list' },
    { permission: 'hytale.accesscontrolmodule.command.ban', command: '/ban' },
    { permission: 'hytale.ambience.command.ambience', command: '/ambience' },
    { permission: 'hytale.ambience.command.ambience.emitter', command: '/ambience emitter' },
    { permission: 'hytale.ambience.command.ambience.emitter.add', command: '/ambience emitter add' },
    { permission: 'hytale.ambience.command.ambience.setmusic', command: '/ambience setmusic' },
    { permission: 'hytale.ambience.command.ambience.clear', command: '/ambience clear' },
    { permission: 'hytale.assetmodule.command.droplist', command: '/droplist' },
    { permission: 'hytale.blocksetmodule.command.blockset', command: '/blockset' },
    { permission: 'hytale.blockspawner.command.blockspawner', command: '/blockspawner' },
    { permission: 'hytale.blockspawner.command.blockspawner.set', command: '/blockspawner set' },
    { permission: 'hytale.blockspawner.command.blockspawner.get', command: '/blockspawner get' },
    { permission: 'hytale.buildertools.command.selectionhistory', command: '/selectionhistory' },
    { permission: 'hytale.buildertools.command.importimage', command: '/importimage' },
    { permission: 'hytale.buildertools.command.gmask.clear', command: '/gmask clear' },
    { permission: 'hytale.buildertools.command.gmask', command: '/gmask' },
    { permission: 'hytale.buildertools.command.prefab', command: '/prefab' },
    { permission: 'hytale.buildertools.command.prefab.list', command: '/prefab list' },
    { permission: 'hytale.buildertools.command.environment', command: '/environment' },
    { permission: 'hytale.buildertools.command.updateselection', command: '/updateselection' },
    { permission: 'hytale.buildertools.command.editprefab', command: '/editprefab' },
    { permission: 'hytale.buildertools.command.editprefab.exit', command: '/editprefab exit' },
    { permission: 'hytale.buildertools.command.editprefab.load', command: '/editprefab load' },
    { permission: 'hytale.buildertools.command.editprefab.new', command: '/editprefab new' },
    { permission: 'hytale.buildertools.command.editprefab.select', command: '/editprefab select' },
    { permission: 'hytale.buildertools.command.editprefab.save', command: '/editprefab save' },
    { permission: 'hytale.buildertools.command.editprefab.saveui', command: '/editprefab saveui' },
    { permission: 'hytale.buildertools.command.editprefab.kill', command: '/editprefab kill' },
    { permission: 'hytale.buildertools.command.editprefab.saveas', command: '/editprefab saveas' },
    { permission: 'hytale.buildertools.command.editprefab.setbox', command: '/editprefab setbox' },
    { permission: 'hytale.buildertools.command.editprefab.info', command: '/editprefab info' },
    { permission: 'hytale.buildertools.command.editprefab.tp', command: '/editprefab tp' },
    { permission: 'hytale.buildertools.command.editprefab.modified', command: '/editprefab modified' },
    { permission: 'hytale.buildertools.command.clearedithistory', command: '/clearedithistory' },
    { permission: 'hytale.buildertools.command.editline', command: '/editline' },
    { permission: 'hytale.buildertools.command.contractselection', command: '/contractselection' },
    { permission: 'hytale.buildertools.command.deselect', command: '/deselect' },
    { permission: 'hytale.buildertools.command.hollow', command: '/hollow' },
    { permission: 'hytale.buildertools.command.extendface', command: '/extendface' },
    { permission: 'hytale.buildertools.command.clearblocks', command: '/clearblocks' },
    { permission: 'hytale.buildertools.command.expand', command: '/expand' },
    { permission: 'hytale.buildertools.command.rotate', command: '/rotate' },
    { permission: 'hytale.buildertools.command.hotbar', command: '/hotbar' },
    { permission: 'hytale.buildertools.command.wall', command: '/wall' },
    { permission: 'hytale.buildertools.command.flip', command: '/flip' },
    { permission: 'hytale.buildertools.command.selectchunksection', command: '/selectchunksection' },
    { permission: 'hytale.buildertools.command.selectchunk', command: '/selectchunk' },
    { permission: 'hytale.buildertools.command.shift', command: '/shift' },
    { permission: 'hytale.buildertools.command.settoolhistorysize', command: '/settoolhistorysize' },
    { permission: 'hytale.buildertools.command.move', command: '/move' },
    { permission: 'hytale.buildertools.command.stack', command: '/stack' },
    { permission: 'hytale.buildertools.command.fillblocks', command: '/fillblocks' },
    { permission: 'hytale.buildertools.command.replace', command: '/replace' },
    { permission: 'hytale.buildertools.command.repairfillers', command: '/repairfillers' },
    { permission: 'hytale.editor.brush.config.clear', command: '/brush config clear' },
    { permission: 'hytale.editor.brush.config.list', command: '/brush config list' },
    { permission: 'hytale.editor.brush.config.step', command: '/brush config step' },
    { permission: 'hytale.editor.brush.config.exit', command: '/brush config exit' },
    { permission: 'hytale.editor.brush.config.load', command: '/brush config load' },
    { permission: 'hytale.editor.brush.config.info', command: '/brush config info' },
    { permission: 'hytale.buildertools.command.submerge', command: '/submerge' },
    { permission: 'hytale.camera.flycam', command: '/flycam' },
    { permission: 'hytale.camera.command.camshake', command: '/camshake' },
    { permission: 'hytale.camera.command.camshake.damage', command: '/camshake damage' },
    { permission: 'hytale.buildertools.command.tint', command: '/tint' },
    { permission: 'hytale.camera.command.camshake.debug', command: '/camshake debug' },
    { permission: 'hytale.collisionmodule.command.hitbox', command: '/hitbox' },
    { permission: 'hytale.collisionmodule.command.hitbox.extents', command: '/hitbox extents' },
    { permission: 'hytale.commandmacro.command.echo', command: '/echo' },
    { permission: 'hytale.commandmacro.command.heal', command: '/heal' },
    { permission: 'hytale.commandmacro.command.noon', command: '/noon' },
    { permission: 'hytale.commandmacro.command.unstuck', command: '/unstuck' },
    { permission: 'hytale.commandmacro.command.settimeandgohome', command: '/settimeandgohome' },
    { permission: 'hytale.commandmacro.command.fillsignature', command: '/fillsignature' },
    { permission: 'hytale.commandmacro.command.delete', command: '/delete' },
    { permission: 'hytale.commandmacro.command.wait', command: '/wait' },
    { permission: 'hytale.commandmacro.command.neardeath', command: '/neardeath' },
    { permission: 'hytale.commandmacro.command.resetrotation', command: '/resetrotation' },
    { permission: 'hytale.consolemodule.command.say', command: '/say' },
    { permission: 'hytale.cosmeticsmodule.command.emote', command: '/emote' },
    { permission: 'hytale.creativehub.command.hub', command: '/hub' },
    { permission: 'hytale.damagemodule.command.desyncdamage', command: '/desyncdamage' },
    { permission: 'hytale.debugplugin.command.debug', command: '/debug' },
    { permission: 'hytale.debugplugin.command.debug.shape', command: '/debug shape' },
    { permission: 'hytale.debugplugin.command.debug.shape.sphere', command: '/debug shape sphere' },
    { permission: 'hytale.debugplugin.command.debug.shape.cube', command: '/debug shape cube' },
    { permission: 'hytale.debugplugin.command.debug.shape.cylinder', command: '/debug shape cylinder' },
    { permission: 'hytale.debugplugin.command.debug.shape.cone', command: '/debug shape cone' },
    { permission: 'hytale.debugplugin.command.debug.shape.arrow', command: '/debug shape arrow' },
    { permission: 'hytale.debugplugin.command.debug.shape.showforce', command: '/debug shape showforce' },
    { permission: 'hytale.debugplugin.command.debug.shape.clear', command: '/debug shape clear' },
    { permission: 'hytale.editor.asset', command: '/editor asset' },
    { permission: 'hytale.editor.packs.create', command: '/editor packs create' },
    { permission: 'hytale.editor.packs.edit', command: '/editor packs edit' },
    { permission: 'hytale.editor.packs.delete', command: '/editor packs delete' },
    { permission: 'hytale.editor.builderTools', command: '/editor buildertools' },
    { permission: 'hytale.editor.brush.use', command: '/editor brush use' },
    { permission: 'hytale.editor.prefab.use', command: '/editor prefab use' },
    { permission: 'hytale.editor.brush.config', command: '/editor brush config' },
    { permission: 'hytale.editor.prefab.manage', command: '/editor prefab manage' },
    { permission: 'hytale.editor.selection.use', command: '/editor selection use' },
    { permission: 'hytale.editor.selection.clipboard', command: '/editor selection clipboard' },
    { permission: 'hytale.editor.selection.modify', command: '/editor selection modify' },
    { permission: 'hytale.editor.history', command: '/editor history' },
    { permission: 'hytale.fluid.command.fluid', command: '/fluid' },
    { permission: 'hytale.fluid.command.fluid.set', command: '/fluid set' },
    { permission: 'hytale.fluid.command.fluid.get', command: '/fluid get' },
    { permission: 'hytale.fluid.command.fluid.setradius', command: '/fluid setradius' },
    { permission: 'hytale.hytalegenerator.command.viewport', command: '/viewport' },
    { permission: 'hytale.i18nmodule.command.lang', command: '/lang' },
    { permission: 'hytale.i18nmodule.command.lang.gen', command: '/lang gen' },
    { permission: 'hytale.i18nmodule.command.toggletmptags', command: '/toggletmptags' },
    { permission: 'hytale.instances.command.instances', command: '/instances' },
    { permission: 'hytale.instances.command.instances.edit', command: '/instances edit' },
    { permission: 'hytale.instances.command.instances.edit.new', command: '/instances edit new' },
    { permission: 'hytale.instances.command.instances.edit.copy', command: '/instances edit copy' },
    { permission: 'hytale.instances.command.instances.edit.load', command: '/instances edit load' },
    { permission: 'hytale.instances.command.instances.edit.list', command: '/instances edit list' },
    { permission: 'hytale.instances.command.instances.exit', command: '/instances exit' },
    { permission: 'hytale.instances.command.instances.migrate', command: '/instances migrate' },
    { permission: 'hytale.instances.command.instances.spawn', command: '/instances spawn' },
    { permission: 'hytale.interactionmodule.command.interaction', command: '/interaction' },
    { permission: 'hytale.interactionmodule.command.interaction.run', command: '/interaction run' },
    { permission: 'hytale.interactionmodule.command.interaction.run.specific', command: '/interaction run specific' },
    { permission: 'hytale.interactionmodule.command.interaction.snapshotsource', command: '/interaction snapshotsource' },
    { permission: 'hytale.interactionmodule.command.interaction.snapshotsource.set', command: '/interaction snapshotsource set' },
    { permission: 'hytale.interactionmodule.command.interaction.clear', command: '/interaction clear' },
    { permission: 'hytale.itemmodule.command.spawnitem', command: '/spawnitem' },
    { permission: 'hytale.landiscovery.command.landiscovery', command: '/landiscovery' },
    { permission: 'hytale.memories.command.memories', command: '/memories' },
    { permission: 'hytale.memories.command.memories.clear', command: '/memories clear' },
    { permission: 'hytale.memories.command.memories.capacity', command: '/memories capacity' },
    { permission: 'hytale.memories.command.memories.level', command: '/memories level' },
    { permission: 'hytale.memories.command.memories.unlockall', command: '/memories unlockall' },
    { permission: 'hytale.model.command.model', command: '/model' },
    { permission: 'hytale.model.command.model.set', command: '/model set' },
    { permission: 'hytale.model.command.model.reset', command: '/model reset' },
    { permission: 'hytale.mounts.command.mount', command: '/mount' },
    { permission: 'hytale.mounts.command.mount.dismount', command: '/mount dismount' },
    { permission: 'hytale.mounts.command.mount.check', command: '/mount check' },
    { permission: 'hytale.npc.command.npc', command: '/npc' },
    { permission: 'hytale.npc.command.npc.all', command: '/npc all' },
    { permission: 'hytale.npc.command.npc.appearance', command: '/npc appearance' },
    { permission: 'hytale.npc.command.npc.attack', command: '/npc attack' },
    { permission: 'hytale.npc.command.npc.attack.clear', command: '/npc attack clear' },
    { permission: 'hytale.npc.command.npc.benchmark', command: '/npc benchmark' },
    { permission: 'hytale.npc.command.npc.blackboard', command: '/npc blackboard' },
    { permission: 'hytale.npc.command.npc.blackboard.chunks', command: '/npc blackboard chunks' },
    { permission: 'hytale.npc.command.npc.blackboard.chunk', command: '/npc blackboard chunk' },
    { permission: 'hytale.npc.command.npc.blackboard.drop', command: '/npc blackboard drop' },
    { permission: 'hytale.npc.command.npc.blackboard.views', command: '/npc blackboard views' },
    { permission: 'hytale.npc.command.npc.blackboard.view', command: '/npc blackboard view' },
    { permission: 'hytale.npc.command.npc.blackboard.blockevents', command: '/npc blackboard blockevents' },
    { permission: 'hytale.npc.command.npc.blackboard.entityevents', command: '/npc blackboard entityevents' },
    { permission: 'hytale.npc.command.npc.blackboard.resourceviews', command: '/npc blackboard resourceviews' },
    { permission: 'hytale.npc.command.npc.blackboard.resourceview', command: '/npc blackboard resourceview' },
    { permission: 'hytale.npc.command.npc.blackboard.reserve', command: '/npc blackboard reserve' },
    { permission: 'hytale.npc.command.npc.blackboard.reservation', command: '/npc blackboard reservation' },
    { permission: 'hytale.npc.command.npc.clean', command: '/npc clean' },
    { permission: 'hytale.npc.command.npc.debug', command: '/npc debug' },
    { permission: 'hytale.npc.command.npc.debug.show', command: '/npc debug show' },
    { permission: 'hytale.npc.command.npc.debug.set', command: '/npc debug set' },
    { permission: 'hytale.npc.command.npc.debug.toggle', command: '/npc debug toggle' },
    { permission: 'hytale.npc.command.npc.debug.defaults', command: '/npc debug defaults' },
    { permission: 'hytale.npc.command.npc.debug.clear', command: '/npc debug clear' },
    { permission: 'hytale.npc.command.npc.debug.presets', command: '/npc debug presets' },
    { permission: 'hytale.npc.command.npc.dump', command: '/npc dump' },
    { permission: 'hytale.npc.command.npc.flock', command: '/npc flock' },
    { permission: 'hytale.npc.command.npc.flock.leave', command: '/npc flock leave' },
    { permission: 'hytale.npc.command.npc.flock.grab', command: '/npc flock grab' },
    { permission: 'hytale.npc.command.npc.flock.join', command: '/npc flock join' },
    { permission: 'hytale.npc.command.npc.flock.playerleave', command: '/npc flock playerleave' },
    { permission: 'hytale.npc.command.npc.freeze', command: '/npc freeze' },
    { permission: 'hytale.npc.command.npc.give', command: '/npc give' },
    { permission: 'hytale.npc.command.npc.give.nothing', command: '/npc give nothing' },
    { permission: 'hytale.npc.command.npc.path', command: '/npc path' },
    { permission: 'hytale.npc.command.npc.path.polygon', command: '/npc path polygon' },
    { permission: 'hytale.npc.command.npc.role', command: '/npc role' },
    { permission: 'hytale.npc.command.npc.runtests', command: '/npc runtests' },
    { permission: 'hytale.npc.command.npc.sensorstats', command: '/npc sensorstats' },
    { permission: 'hytale.npc.command.npc.spawn', command: '/npc spawn' },
    { permission: 'hytale.npc.command.npc.step', command: '/npc step' },
    { permission: 'hytale.npc.command.npc.test', command: '/npc test' },
    { permission: 'hytale.npc.command.npc.test.probe', command: '/npc test probe' },
    { permission: 'hytale.npc.command.npc.thaw', command: '/npc thaw' },
    { permission: 'hytale.npc.command.npc.message', command: '/npc message' },
    { permission: 'hytale.objectives.command.objective', command: '/objective' },
    { permission: 'hytale.objectives.command.objective.start', command: '/objective start' },
    { permission: 'hytale.objectives.command.objective.start.objective', command: '/objective start objective' },
    { permission: 'hytale.objectives.command.objective.start.line', command: '/objective start line' },
    { permission: 'hytale.objectives.command.objective.complete', command: '/objective complete' },
    { permission: 'hytale.objectives.command.objective.complete.task', command: '/objective complete task' },
    { permission: 'hytale.objectives.command.objective.complete.taskset', command: '/objective complete taskset' },
    { permission: 'hytale.objectives.command.objective.complete.objective', command: '/objective complete objective' },
    { permission: 'hytale.objectives.command.objective.panel', command: '/objective panel' },
    { permission: 'hytale.objectives.command.objective.history', command: '/objective history' },
    { permission: 'hytale.objectives.command.objective.locationmarker', command: '/objective locationmarker' },
    { permission: 'hytale.objectives.command.objective.locationmarker.add', command: '/objective locationmarker add' },
    { permission: 'hytale.objectives.command.objective.locationmarker.enable', command: '/objective locationmarker enable' },
    { permission: 'hytale.objectives.command.objective.locationmarker.disable', command: '/objective locationmarker disable' },
    { permission: 'hytale.objectives.command.objective.reachlocationmarker', command: '/objective reachlocationmarker' },
    { permission: 'hytale.objectives.command.objective.reachlocationmarker.add', command: '/objective reachlocationmarker add' },
    { permission: 'hytale.parkour.command.checkpoint', command: '/checkpoint' },
    { permission: 'hytale.parkour.command.checkpoint.remove', command: '/checkpoint remove' },
    { permission: 'hytale.parkour.command.checkpoint.add', command: '/checkpoint add' },
    { permission: 'hytale.parkour.command.checkpoint.reset', command: '/checkpoint reset' },
    { permission: 'hytale.path.command.path', command: '/path' },
    { permission: 'hytale.path.command.path.list', command: '/path list' },
    { permission: 'hytale.path.command.path.nodes', command: '/path nodes' },
    { permission: 'hytale.path.command.path.new', command: '/path new' },
    { permission: 'hytale.path.command.path.edit', command: '/path edit' },
    { permission: 'hytale.path.command.path.add', command: '/path add' },
    { permission: 'hytale.path.command.path.merge', command: '/path merge' },
    { permission: 'hytale.path.command.path.update', command: '/path update' },
    { permission: 'hytale.path.command.path.update.pause', command: '/path update pause' },
    { permission: 'hytale.path.command.path.update.observationangle', command: '/path update observationangle' },
    { permission: 'hytale.path.command.worldpath', command: '/worldpath' },
    { permission: 'hytale.path.command.worldpath.list', command: '/worldpath list' },
    { permission: 'hytale.path.command.worldpath.remove', command: '/worldpath remove' },
    { permission: 'hytale.path.command.worldpath.save', command: '/worldpath save' },
    { permission: 'hytale.path.command.worldpath.builder', command: '/worldpath builder' },
    { permission: 'hytale.path.command.worldpath.builder.stop', command: '/worldpath builder stop' },
    { permission: 'hytale.path.command.worldpath.builder.load', command: '/worldpath builder load' },
    { permission: 'hytale.path.command.worldpath.builder.simulate', command: '/worldpath builder simulate' },
    { permission: 'hytale.path.command.worldpath.builder.clear', command: '/worldpath builder clear' },
    { permission: 'hytale.path.command.worldpath.builder.add', command: '/worldpath builder add' },
    { permission: 'hytale.path.command.worldpath.builder.set', command: '/worldpath builder set' },
    { permission: 'hytale.path.command.worldpath.builder.goto', command: '/worldpath builder goto' },
    { permission: 'hytale.path.command.worldpath.builder.remove', command: '/worldpath builder remove' },
    { permission: 'hytale.path.command.worldpath.builder.save', command: '/worldpath builder save' },
    { permission: 'hytale.permissionsmodule.command.perm', command: '/perm' },
    { permission: 'hytale.permissionsmodule.command.perm.group', command: '/perm group' },
    { permission: 'hytale.permissionsmodule.command.perm.group.list', command: '/perm group list' },
    { permission: 'hytale.permissionsmodule.command.perm.group.add', command: '/perm group add' },
    { permission: 'hytale.permissionsmodule.command.perm.group.remove', command: '/perm group remove' },
    { permission: 'hytale.permissionsmodule.command.perm.user', command: '/perm user' },
    { permission: 'hytale.permissionsmodule.command.perm.user.list', command: '/perm user list' },
    { permission: 'hytale.permissionsmodule.command.perm.user.add', command: '/perm user add' },
    { permission: 'hytale.permissionsmodule.command.perm.user.remove', command: '/perm user remove' },
    { permission: 'hytale.permissionsmodule.command.perm.user.group', command: '/perm user group' },
    { permission: 'hytale.permissionsmodule.command.perm.user.group.list', command: '/perm user group list' },
    { permission: 'hytale.permissionsmodule.command.perm.user.group.add', command: '/perm user group add' },
    { permission: 'hytale.permissionsmodule.command.perm.user.group.remove', command: '/perm user group remove' },
    { permission: 'hytale.permissionsmodule.command.perm.test', command: '/perm test' },
    { permission: 'hytale.command.op.add', command: '/op add' },
    { permission: 'hytale.command.op.remove', command: '/op remove' },
    { permission: 'hytale.portals.command.cursethis', command: '/cursethis' },
    { permission: 'hytale.portals.command.leave', command: '/leave' },
    { permission: 'hytale.portals.command.voidevent', command: '/voidevent' },
    { permission: 'hytale.portals.command.voidevent.start', command: '/voidevent start' },
    { permission: 'hytale.portals.command.fragment', command: '/fragment' },
    { permission: 'hytale.portals.command.fragment.timer', command: '/fragment timer' },
    { permission: 'hytale.prefabspawnermodule.command.prefabspawner', command: '/prefabspawner' },
    { permission: 'hytale.prefabspawnermodule.command.prefabspawner.get', command: '/prefabspawner get' },
    { permission: 'hytale.prefabspawnermodule.command.prefabspawner.set', command: '/prefabspawner set' },
    { permission: 'hytale.prefabspawnermodule.command.prefabspawner.weight', command: '/prefabspawner weight' },
    { permission: 'hytale.reputation.command.reputation', command: '/reputation' },
    { permission: 'hytale.reputation.command.reputation.add', command: '/reputation add' },
    { permission: 'hytale.reputation.command.reputation.set', command: '/reputation set' },
    { permission: 'hytale.reputation.command.reputation.rank', command: '/reputation rank' },
    { permission: 'hytale.reputation.command.reputation.value', command: '/reputation value' },
    { permission: 'hytale.servermanager.command.bindings', command: '/bindings' },
    { permission: 'hytale.singleplayermodule.command.play', command: '/play' },
    { permission: 'hytale.singleplayermodule.command.play.lan', command: '/play lan' },
    { permission: 'hytale.singleplayermodule.command.play.friend', command: '/play friend' },
    { permission: 'hytale.singleplayermodule.command.play.online', command: '/play online' },
    { permission: 'hytale.spawning.command.spawning', command: '/spawning' },
    { permission: 'hytale.spawning.command.spawning.enable', command: '/spawning enable' },
    { permission: 'hytale.spawning.command.spawning.disable', command: '/spawning disable' },
    { permission: 'hytale.spawning.command.spawning.beacons', command: '/spawning beacons' },
    { permission: 'hytale.spawning.command.spawning.beacons.add', command: '/spawning beacons add' },
    { permission: 'hytale.spawning.command.spawning.beacons.trigger', command: '/spawning beacons trigger' },
    { permission: 'hytale.spawning.command.spawning.markers', command: '/spawning markers' },
    { permission: 'hytale.spawning.command.spawning.markers.enable', command: '/spawning markers enable' },
    { permission: 'hytale.spawning.command.spawning.markers.disable', command: '/spawning markers disable' },
    { permission: 'hytale.spawning.command.spawning.markers.add', command: '/spawning markers add' },
    { permission: 'hytale.spawning.command.spawning.populate', command: '/spawning populate' },
    { permission: 'hytale.spawning.command.spawning.stats', command: '/spawning stats' },
    { permission: 'hytale.spawning.command.spawning.suppression', command: '/spawning suppression' },
    { permission: 'hytale.spawning.command.spawning.suppression.dump', command: '/spawning suppression dump' },
    { permission: 'hytale.spawning.command.spawning.suppression.dumpall', command: '/spawning suppression dumpall' },
    { permission: 'hytale.spawning.command.spawning.suppression.add', command: '/spawning suppression add' },
    { permission: 'hytale.system.command.ping', command: '/ping' },
    { permission: 'hytale.system.command.ping.clear', command: '/ping clear' },
    { permission: 'hytale.system.command.ping.graph', command: '/ping graph' },
    { permission: 'hytale.system.command.plugin', command: '/plugin' },
    { permission: 'hytale.system.command.plugin.list', command: '/plugin list' },
    { permission: 'hytale.system.command.plugin.load', command: '/plugin load' },
    { permission: 'hytale.system.command.plugin.unload', command: '/plugin unload' },
    { permission: 'hytale.system.command.plugin.reload', command: '/plugin reload' },
    { permission: 'hytale.system.command.plugin.manage', command: '/plugin manage' },
    { permission: 'hytale.command.whereami.self', command: '/whereami' },
    { permission: 'hytale.system.command.stresstest', command: '/stresstest' },
    { permission: 'hytale.system.command.stresstest.start', command: '/stresstest start' },
    { permission: 'hytale.system.command.stresstest.stop', command: '/stresstest stop' },
    { permission: 'hytale.system.command.packetstats', command: '/packetstats' },
    { permission: 'hytale.system.command.worldmap', command: '/worldmap' },
    { permission: 'hytale.system.command.worldmap.reload', command: '/worldmap reload' },
    { permission: 'hytale.system.command.worldmap.discover', command: '/worldmap discover' },
    { permission: 'hytale.system.command.worldmap.undiscover', command: '/worldmap undiscover' },
    { permission: 'hytale.system.command.worldmap.clearmarkers', command: '/worldmap clearmarkers' },
    { permission: 'hytale.system.command.worldmap.viewradius', command: '/worldmap viewradius' },
    { permission: 'hytale.system.command.worldmap.viewradius.get', command: '/worldmap viewradius get' },
    { permission: 'hytale.system.command.worldmap.viewradius.set', command: '/worldmap viewradius set' },
    { permission: 'hytale.system.command.worldmap.viewradius.remove', command: '/worldmap viewradius remove' },
    { permission: 'hytale.system.command.hitboxcollision', command: '/hitboxcollision' },
    { permission: 'hytale.system.command.hitboxcollision.add', command: '/hitboxcollision add' },
    { permission: 'hytale.system.command.hitboxcollision.add.entity', command: '/hitboxcollision add entity' },
    { permission: 'hytale.system.command.hitboxcollision.add.self', command: '/hitboxcollision add self' },
    { permission: 'hytale.system.command.hitboxcollision.remove', command: '/hitboxcollision remove' },
    { permission: 'hytale.system.command.hitboxcollision.remove.entity', command: '/hitboxcollision remove entity' },
    { permission: 'hytale.system.command.hitboxcollision.remove.self', command: '/hitboxcollision remove self' },
    { permission: 'hytale.system.command.debugplayerposition', command: '/debugplayerposition' },
    { permission: 'hytale.system.command.log', command: '/log' },
    { permission: 'hytale.system.command.sound', command: '/sound' },
    { permission: 'hytale.system.command.sound.2d', command: '/sound 2d' },
    { permission: 'hytale.system.command.sound.3d', command: '/sound 3d' },
    { permission: 'hytale.system.command.stash', command: '/stash' },
    { permission: 'hytale.system.command.help', command: '/help' },
    { permission: 'hytale.system.command.tagpattern', command: '/tagpattern' },
    { permission: 'hytale.system.command.weather', command: '/weather' },
    { permission: 'hytale.system.command.weather.set', command: '/weather set' },
    { permission: 'hytale.system.command.weather.get', command: '/weather get' },
    { permission: 'hytale.system.command.weather.reset', command: '/weather reset' },
    { permission: 'hytale.system.command.hitdetection', command: '/hitdetection' },
    { permission: 'hytale.system.command.networkchunksending', command: '/networkchunksending' },
    { permission: 'hytale.system.command.entity', command: '/entity' },
    { permission: 'hytale.system.command.entity.clone', command: '/entity clone' },
    { permission: 'hytale.system.command.entity.remove', command: '/entity remove' },
    { permission: 'hytale.system.command.entity.dump', command: '/entity dump' },
    { permission: 'hytale.system.command.entity.clean', command: '/entity clean' },
    { permission: 'hytale.system.command.entity.lod', command: '/entity lod' },
    { permission: 'hytale.system.command.entity.lod.default', command: '/entity lod default' },
    { permission: 'hytale.system.command.entity.tracker', command: '/entity tracker' },
    { permission: 'hytale.system.command.entity.resend', command: '/entity resend' },
    { permission: 'hytale.system.command.entity.nameplate', command: '/entity nameplate' },
    { permission: 'hytale.system.command.entity.stats', command: '/entity stats' },
    { permission: 'hytale.system.command.entity.stats.dump', command: '/entity stats dump' },
    { permission: 'hytale.system.command.entity.stats.get', command: '/entity stats get' },
    { permission: 'hytale.system.command.entity.stats.set', command: '/entity stats set' },
    { permission: 'hytale.system.command.entity.stats.settomax', command: '/entity stats settomax' },
    { permission: 'hytale.system.command.entity.stats.reset', command: '/entity stats reset' },
    { permission: 'hytale.system.command.entity.stats.add', command: '/entity stats add' },
    { permission: 'hytale.system.command.entity.snapshot', command: '/entity snapshot' },
    { permission: 'hytale.system.command.entity.snapshot.length', command: '/entity snapshot length' },
    { permission: 'hytale.system.command.entity.snapshot.history', command: '/entity snapshot history' },
    { permission: 'hytale.system.command.entity.effect', command: '/entity effect' },
    { permission: 'hytale.system.command.entity.interactable', command: '/entity interactable' },
    { permission: 'hytale.system.command.entity.intangible', command: '/entity intangible' },
    { permission: 'hytale.system.command.entity.invulnerable', command: '/entity invulnerable' },
    { permission: 'hytale.system.command.entity.hidefromadventureplayers', command: '/entity hidefromadventureplayers' },
    { permission: 'hytale.system.command.entity.count', command: '/entity count' },
    { permission: 'hytale.system.command.sudo', command: '/sudo' },
    { permission: 'hytale.system.command.maxplayers', command: '/maxplayers' },
    { permission: 'hytale.system.command.hide', command: '/hide' },
    { permission: 'hytale.system.command.hide.show', command: '/hide show' },
    { permission: 'hytale.system.command.hide.showall', command: '/hide showall' },
    { permission: 'hytale.system.command.hide.all', command: '/hide all' },
    { permission: 'hytale.system.command.inventory', command: '/inventory' },
    { permission: 'hytale.system.command.inventory.clear', command: '/inventory clear' },
    { permission: 'hytale.system.command.inventory.see', command: '/inventory see' },
    { permission: 'hytale.system.command.inventory.item', command: '/inventory item' },
    { permission: 'hytale.system.command.inventory.backpack', command: '/inventory backpack' },
    { permission: 'hytale.system.command.chunk', command: '/chunk' },
    { permission: 'hytale.system.command.chunk.fixheight', command: '/chunk fixheight' },
    { permission: 'hytale.system.command.chunk.forcetick', command: '/chunk forcetick' },
    { permission: 'hytale.system.command.chunk.info', command: '/chunk info' },
    { permission: 'hytale.system.command.chunk.lighting', command: '/chunk lighting' },
    { permission: 'hytale.system.command.chunk.load', command: '/chunk load' },
    { permission: 'hytale.system.command.chunk.loaded', command: '/chunk loaded' },
    { permission: 'hytale.system.command.chunk.marksave', command: '/chunk marksave' },
    { permission: 'hytale.system.command.chunk.maxsendrate', command: '/chunk maxsendrate' },
    { permission: 'hytale.system.command.chunk.regenerate', command: '/chunk regenerate' },
    { permission: 'hytale.system.command.chunk.resend', command: '/chunk resend' },
    { permission: 'hytale.system.command.chunk.tint', command: '/chunk tint' },
    { permission: 'hytale.system.command.chunk.tracker', command: '/chunk tracker' },
    { permission: 'hytale.system.command.chunk.unload', command: '/chunk unload' },
    { permission: 'hytale.system.command.particle', command: '/particle' },
    { permission: 'hytale.system.command.particle.spawn', command: '/particle spawn' },
    { permission: 'hytale.system.command.spawnblock', command: '/spawnblock' },
    { permission: 'hytale.system.command.kick', command: '/kick' },
    { permission: 'hytale.command.give.self', command: '/give' },
    { permission: 'hytale.command.give.self.armor', command: '/give armor' },
    { permission: 'hytale.system.command.pidcheck', command: '/pidcheck' },
    { permission: 'hytale.system.command.update', command: '/update' },
    { permission: 'hytale.system.command.update.assets', command: '/update assets' },
    { permission: 'hytale.system.command.update.assets.status', command: '/update assets status' },
    { permission: 'hytale.system.command.update.assets.reset', command: '/update assets reset' },
    { permission: 'hytale.system.command.update.assets.pull', command: '/update assets pull' },
    { permission: 'hytale.system.command.update.prefabs', command: '/update prefabs' },
    { permission: 'hytale.system.command.update.prefabs.status', command: '/update prefabs status' },
    { permission: 'hytale.system.command.update.prefabs.commit', command: '/update prefabs commit' },
    { permission: 'hytale.system.command.update.prefabs.pull', command: '/update prefabs pull' },
    { permission: 'hytale.system.command.update.prefabs.push', command: '/update prefabs push' },
    { permission: 'hytale.system.command.update.prefabs.all', command: '/update prefabs all' },
    { permission: 'hytale.system.command.notify', command: '/notify' },
    { permission: 'hytale.system.command.auth', command: '/auth' },
    { permission: 'hytale.system.command.auth.login', command: '/auth login' },
    { permission: 'hytale.system.command.auth.status', command: '/auth status' },
    { permission: 'hytale.system.command.auth.login.browser', command: '/auth login browser' },
    { permission: 'hytale.system.command.auth.login.device', command: '/auth login device' },
    { permission: 'hytale.system.command.auth.select', command: '/auth select' },
    { permission: 'hytale.system.command.auth.logout', command: '/auth logout' },
    { permission: 'hytale.system.command.auth.cancel', command: '/auth cancel' },
    { permission: 'hytale.system.command.auth.persistence', command: '/auth persistence' },
    { permission: 'hytale.system.command.itemstate', command: '/itemstate' },
    { permission: 'hytale.system.command.network', command: '/network' },
    { permission: 'hytale.system.command.network.latencysimulation', command: '/network latencysimulation' },
    { permission: 'hytale.system.command.network.latencysimulation.set', command: '/network latencysimulation set' },
    { permission: 'hytale.system.command.network.latencysimulation.reset', command: '/network latencysimulation reset' },
    { permission: 'hytale.system.command.network.serverknockback', command: '/network serverknockback' },
    { permission: 'hytale.system.command.network.debugknockback', command: '/network debugknockback' },
    { permission: 'hytale.system.command.packs', command: '/packs' },
    { permission: 'hytale.system.command.packs.list', command: '/packs list' },
    { permission: 'hytale.system.command.hudtest', command: '/hudtest' },
    { permission: 'hytale.command.kill.self', command: '/kill' },
    { permission: 'hytale.system.command.convertprefabs', command: '/convertprefabs' },
    { permission: 'hytale.system.command.recipe', command: '/recipe' },
    { permission: 'hytale.system.command.recipe.learn', command: '/recipe learn' },
    { permission: 'hytale.system.command.recipe.forget', command: '/recipe forget' },
    { permission: 'hytale.system.command.recipe.list', command: '/recipe list' },
    { permission: 'hytale.system.command.sleep', command: '/sleep' },
    { permission: 'hytale.system.command.sleep.offset', command: '/sleep offset' },
    { permission: 'hytale.system.command.sleep.test', command: '/sleep test' },
    { permission: 'hytale.system.command.backup', command: '/backup' },
    { permission: 'hytale.system.command.commands', command: '/commands' },
    { permission: 'hytale.system.command.commands.dump', command: '/commands dump' },
    { permission: 'hytale.command.damage.self', command: '/damage' },
    { permission: 'hytale.system.command.player', command: '/player' },
    { permission: 'hytale.system.command.player.reset', command: '/player reset' },
    { permission: 'hytale.system.command.player.stats', command: '/player stats' },
    { permission: 'hytale.system.command.player.stats.add', command: '/player stats add' },
    { permission: 'hytale.system.command.player.stats.get', command: '/player stats get' },
    { permission: 'hytale.system.command.player.stats.set', command: '/player stats set' },
    { permission: 'hytale.system.command.player.stats.settomax', command: '/player stats settomax' },
    { permission: 'hytale.system.command.player.stats.dump', command: '/player stats dump' },
    { permission: 'hytale.system.command.player.stats.reset', command: '/player stats reset' },
    { permission: 'hytale.system.command.player.effect', command: '/player effect' },
    { permission: 'hytale.command.player.effect.apply.self', command: '/player effect apply' },
    { permission: 'hytale.command.player.effect.clear.self', command: '/player effect clear' },
    { permission: 'hytale.system.command.player.respawn', command: '/player respawn' },
    { permission: 'hytale.system.command.player.camera', command: '/player camera' },
    { permission: 'hytale.system.command.player.camera.reset', command: '/player camera reset' },
    { permission: 'hytale.system.command.player.camera.topdown', command: '/player camera topdown' },
    { permission: 'hytale.system.command.player.camera.sidescroller', command: '/player camera sidescroller' },
    { permission: 'hytale.system.command.player.camera.demo', command: '/player camera demo' },
    { permission: 'hytale.system.command.player.camera.demo.activate', command: '/player camera demo activate' },
    { permission: 'hytale.system.command.player.camera.demo.deactivate', command: '/player camera demo deactivate' },
    { permission: 'hytale.system.command.player.viewradius', command: '/player viewradius' },
    { permission: 'hytale.system.command.player.viewradius.get', command: '/player viewradius get' },
    { permission: 'hytale.system.command.player.viewradius.set', command: '/player viewradius set' },
    { permission: 'hytale.system.command.player.zone', command: '/player zone' },
    { permission: 'hytale.system.command.messagetest', command: '/messagetest' },
    { permission: 'hytale.system.command.repulsion', command: '/repulsion' },
    { permission: 'hytale.system.command.repulsion.add', command: '/repulsion add' },
    { permission: 'hytale.system.command.repulsion.add.entity', command: '/repulsion add entity' },
    { permission: 'hytale.system.command.repulsion.add.self', command: '/repulsion add self' },
    { permission: 'hytale.system.command.repulsion.remove', command: '/repulsion remove' },
    { permission: 'hytale.system.command.repulsion.remove.entity', command: '/repulsion remove entity' },
    { permission: 'hytale.system.command.repulsion.remove.self', command: '/repulsion remove self' },
    { permission: 'hytale.system.command.worldgen', command: '/worldgen' },
    { permission: 'hytale.system.command.worldgen.benchmark', command: '/worldgen benchmark' },
    { permission: 'hytale.system.command.worldgen.reload', command: '/worldgen reload' },
    { permission: 'hytale.system.command.validatecpb', command: '/validatecpb' },
    { permission: 'hytale.system.command.lighting', command: '/lighting' },
    { permission: 'hytale.system.command.lighting.calculation', command: '/lighting calculation' },
    { permission: 'hytale.system.command.lighting.get', command: '/lighting get' },
    { permission: 'hytale.system.command.lighting.invalidate', command: '/lighting invalidate' },
    { permission: 'hytale.system.command.lighting.info', command: '/lighting info' },
    { permission: 'hytale.system.command.lighting.send', command: '/lighting send' },
    { permission: 'hytale.system.command.lighting.send.local', command: '/lighting send local' },
    { permission: 'hytale.system.command.lighting.send.global', command: '/lighting send global' },
    { permission: 'hytale.system.command.version', command: '/version' },
    { permission: 'hytale.system.command.stop', command: '/stop' },
    { permission: 'hytale.system.command.who', command: '/who' },
    { permission: 'hytale.system.command.server', command: '/server' },
    { permission: 'hytale.system.command.server.stats', command: '/server stats' },
    { permission: 'hytale.system.command.server.stats.cpu', command: '/server stats cpu' },
    { permission: 'hytale.system.command.server.stats.memory', command: '/server stats memory' },
    { permission: 'hytale.system.command.server.stats.gc', command: '/server stats gc' },
    { permission: 'hytale.system.command.server.gc', command: '/server gc' },
    { permission: 'hytale.system.command.server.dump', command: '/server dump' },
    { permission: 'hytale.system.command.whoami', command: '/whoami' },
    { permission: 'hytale.system.command.eventtitle', command: '/eventtitle' },
    { permission: 'hytale.system.command.buildertoolslegend', command: '/buildertoolslegend' },
    { permission: 'hytale.system.command.toggleblockplacementoverride', command: '/toggleblockplacementoverride' },
    { permission: 'hytale.system.command.assets', command: '/assets' },
    { permission: 'hytale.system.command.assets.tags', command: '/assets tags' },
    { permission: 'hytale.system.command.assets.duplicates', command: '/assets duplicates' },
    { permission: 'hytale.system.command.assets.longest', command: '/assets longest' },
    { permission: 'hytale.command.gamemode.self', command: '/gamemode' },
    { permission: 'hytale.system.command.refer', command: '/refer' },
    { permission: 'hytale.teleport.command.warp', command: '/warp' },
    { permission: 'hytale.command.warp.go', command: '/warp go' },
    { permission: 'hytale.command.warp.set', command: '/warp set' },
    { permission: 'hytale.command.warp.list', command: '/warp list' },
    { permission: 'hytale.command.warp.remove', command: '/warp remove' },
    { permission: 'hytale.command.warp.reload', command: '/warp reload' },
    { permission: 'hytale.command.spawn.self', command: '/spawn' },
    { permission: 'hytale.command.spawn.self.set', command: '/spawn set' },
    { permission: 'hytale.command.spawn.self.default', command: '/spawn default' },
    { permission: 'hytale.teleport.command.tp', command: '/tp' },
    { permission: 'hytale.command.teleport.all', command: '/teleport all' },
    { permission: 'hytale.command.teleport.home', command: '/teleport home' },
    { permission: 'hytale.command.teleport.top', command: '/teleport top' },
    { permission: 'hytale.command.teleport.back', command: '/teleport back' },
    { permission: 'hytale.command.teleport.forward', command: '/teleport forward' },
    { permission: 'hytale.command.teleport.history', command: '/teleport history' },
    { permission: 'hytale.command.teleport.world', command: '/teleport world' },
    { permission: 'hytale.timemodule.command.time', command: '/time' },
    { permission: 'hytale.timemodule.command.time.dawn', command: '/time dawn' },
    { permission: 'hytale.timemodule.command.time.midday', command: '/time midday' },
    { permission: 'hytale.timemodule.command.time.dusk', command: '/time dusk' },
    { permission: 'hytale.timemodule.command.time.midnight', command: '/time midnight' },
    { permission: 'hytale.timemodule.command.time.set', command: '/time set' },
    { permission: 'hytale.timemodule.command.time.set.dawn', command: '/time set dawn' },
    { permission: 'hytale.timemodule.command.time.set.midday', command: '/time set midday' },
    { permission: 'hytale.timemodule.command.time.set.dusk', command: '/time set dusk' },
    { permission: 'hytale.timemodule.command.time.set.midnight', command: '/time set midnight' },
    { permission: 'hytale.timemodule.command.time.pause', command: '/time pause' },
    { permission: 'hytale.timemodule.command.time.dilation', command: '/time dilation' },
    { permission: 'hytale.universe.command.blockselect', command: '/blockselect' },
    { permission: 'hytale.universe.command.world', command: '/world' },
    { permission: 'hytale.universe.command.world.list', command: '/world list' },
    { permission: 'hytale.universe.command.world.remove', command: '/world remove' },
    { permission: 'hytale.universe.command.world.prune', command: '/world prune' },
    { permission: 'hytale.universe.command.world.load', command: '/world load' },
    { permission: 'hytale.universe.command.world.add', command: '/world add' },
    { permission: 'hytale.universe.command.world.setdefault', command: '/world setdefault' },
    { permission: 'hytale.universe.command.world.save', command: '/world save' },
    { permission: 'hytale.universe.command.world.pause', command: '/world pause' },
    { permission: 'hytale.universe.command.world.config', command: '/world config' },
    { permission: 'hytale.universe.command.world.config.pausetime', command: '/world config pausetime' },
    { permission: 'hytale.universe.command.world.config.seed', command: '/world config seed' },
    { permission: 'hytale.universe.command.world.config.setspawn', command: '/world config setspawn' },
    { permission: 'hytale.universe.command.world.config.pvp', command: '/world config pvp' },
    { permission: 'hytale.universe.command.world.config.setspawn.default', command: '/world config setspawn default' },
    { permission: 'hytale.universe.command.world.settings', command: '/world settings' },
    { permission: 'hytale.universe.command.world.settings.worldgentype', command: '/world settings worldgentype' },
    { permission: 'hytale.universe.command.world.settings.worldgentype.set', command: '/world settings worldgentype set' },
    { permission: 'hytale.universe.command.world.settings.worldgentype.reset', command: '/world settings worldgentype reset' },
    { permission: 'hytale.universe.command.world.settings.worldmaptype', command: '/world settings worldmaptype' },
    { permission: 'hytale.universe.command.world.settings.worldmaptype.set', command: '/world settings worldmaptype set' },
    { permission: 'hytale.universe.command.world.settings.worldmaptype.reset', command: '/world settings worldmaptype reset' },
    { permission: 'hytale.universe.command.world.settings.chunkstoragetype.set', command: '/world settings chunkstoragetype set' },
    { permission: 'hytale.universe.command.world.settings.chunkstoragetype', command: '/world settings chunkstoragetype' },
    { permission: 'hytale.universe.command.world.settings.chunkstoragetype.reset', command: '/world settings chunkstoragetype reset' },
    { permission: 'hytale.universe.command.world.settings.ticking', command: '/world settings ticking' },
    { permission: 'hytale.universe.command.world.settings.ticking.set', command: '/world settings ticking set' },
    { permission: 'hytale.universe.command.world.settings.ticking.reset', command: '/world settings ticking reset' },
    { permission: 'hytale.universe.command.world.settings.blockticking', command: '/world settings blockticking' },
    { permission: 'hytale.universe.command.world.settings.blockticking.set', command: '/world settings blockticking set' },
    { permission: 'hytale.universe.command.world.settings.blockticking.reset', command: '/world settings blockticking reset' },
    { permission: 'hytale.universe.command.world.settings.pvp', command: '/world settings pvp' },
    { permission: 'hytale.universe.command.world.settings.pvp.set', command: '/world settings pvp set' },
    { permission: 'hytale.universe.command.world.settings.pvp.reset', command: '/world settings pvp reset' },
    { permission: 'hytale.universe.command.world.settings.timepaused', command: '/world settings timepaused' },
    { permission: 'hytale.universe.command.world.settings.timepaused.set', command: '/world settings timepaused set' },
    { permission: 'hytale.universe.command.world.settings.timepaused.reset', command: '/world settings timepaused reset' },
    { permission: 'hytale.universe.command.world.settings.spawningnpc', command: '/world settings spawningnpc' },
    { permission: 'hytale.universe.command.world.settings.spawningnpc.set', command: '/world settings spawningnpc set' },
    { permission: 'hytale.universe.command.world.settings.spawningnpc.reset', command: '/world settings spawningnpc reset' },
    { permission: 'hytale.universe.command.world.settings.spawnmarkers', command: '/world settings spawnmarkers' },
    { permission: 'hytale.universe.command.world.settings.spawnmarkers.set', command: '/world settings spawnmarkers set' },
    { permission: 'hytale.universe.command.world.settings.spawnmarkers.reset', command: '/world settings spawnmarkers reset' },
    { permission: 'hytale.universe.command.world.settings.freezeallnpcs', command: '/world settings freezeallnpcs' },
    { permission: 'hytale.universe.command.world.settings.freezeallnpcs.set', command: '/world settings freezeallnpcs set' },
    { permission: 'hytale.universe.command.world.settings.freezeallnpcs.reset', command: '/world settings freezeallnpcs reset' },
    { permission: 'hytale.universe.command.world.settings.compassupdating', command: '/world settings compassupdating' },
    { permission: 'hytale.universe.command.world.settings.compassupdating.set', command: '/world settings compassupdating set' },
    { permission: 'hytale.universe.command.world.settings.compassupdating.reset', command: '/world settings compassupdating reset' },
    { permission: 'hytale.universe.command.world.settings.playersaving', command: '/world settings playersaving' },
    { permission: 'hytale.universe.command.world.settings.playersaving.set', command: '/world settings playersaving set' },
    { permission: 'hytale.universe.command.world.settings.playersaving.reset', command: '/world settings playersaving reset' },
    { permission: 'hytale.universe.command.world.settings.chunksaving', command: '/world settings chunksaving' },
    { permission: 'hytale.universe.command.world.settings.chunksaving.set', command: '/world settings chunksaving set' },
    { permission: 'hytale.universe.command.world.settings.chunksaving.reset', command: '/world settings chunksaving reset' },
    { permission: 'hytale.universe.command.world.settings.chunkunloading', command: '/world settings chunkunloading' },
    { permission: 'hytale.universe.command.world.settings.chunkunloading.set', command: '/world settings chunkunloading set' },
    { permission: 'hytale.universe.command.world.settings.chunkunloading.reset', command: '/world settings chunkunloading reset' },
    { permission: 'hytale.universe.command.world.settings.gamemode.set', command: '/world settings gamemode set' },
    { permission: 'hytale.universe.command.world.settings.gamemode.reset', command: '/world settings gamemode reset' },
    { permission: 'hytale.universe.command.world.settings.gameplayconfig', command: '/world settings gameplayconfig' },
    { permission: 'hytale.universe.command.world.settings.gamemode', command: '/world settings gamemode' },
    { permission: 'hytale.universe.command.world.settings.gameplayconfig.set', command: '/world settings gameplayconfig set' },
    { permission: 'hytale.universe.command.world.settings.gameplayconfig.reset', command: '/world settings gameplayconfig reset' },
    { permission: 'hytale.universe.command.world.settings.pregenerate', command: '/world settings pregenerate' },
    { permission: 'hytale.universe.command.world.settings.pregenerate.set', command: '/world settings pregenerate set' },
    { permission: 'hytale.universe.command.world.settings.pregenerate.reset', command: '/world settings pregenerate reset' },
    { permission: 'hytale.universe.command.world.settings.keeploaded', command: '/world settings keeploaded' },
    { permission: 'hytale.universe.command.world.settings.keeploaded.set', command: '/world settings keeploaded set' },
    { permission: 'hytale.universe.command.world.settings.keeploaded.reset', command: '/world settings keeploaded reset' },
    { permission: 'hytale.universe.command.world.perf', command: '/world perf' },
    { permission: 'hytale.universe.command.world.perf.graph', command: '/world perf graph' },
    { permission: 'hytale.universe.command.world.perf.reset', command: '/world perf reset' },
    { permission: 'hytale.universe.command.world.tps', command: '/world tps' },
    { permission: 'hytale.universe.command.world.tps.reset', command: '/world tps reset' },
    { permission: 'hytale.universe.command.block', command: '/block' },
    { permission: 'hytale.universe.command.block.set', command: '/block set' },
    { permission: 'hytale.universe.command.block.setticking', command: '/block setticking' },
    { permission: 'hytale.universe.command.block.get', command: '/block get' },
    { permission: 'hytale.universe.command.block.getstate', command: '/block getstate' },
    { permission: 'hytale.universe.command.block.row', command: '/block row' },
    { permission: 'hytale.universe.command.block.bulk', command: '/block bulk' },
    { permission: 'hytale.universe.command.block.bulk.find', command: '/block bulk find' },
    { permission: 'hytale.universe.command.block.bulk.find-here', command: '/block bulk find-here' },
    { permission: 'hytale.universe.command.block.bulk.replace', command: '/block bulk replace' },
    { permission: 'hytale.universe.command.block.inspectfiller', command: '/block inspectfiller' },
    { permission: 'hytale.universe.command.block.inspectrotation', command: '/block inspectrotation' },
    { permission: 'hytale.universe.command.block.setstate', command: '/block setstate' },
    { permission: 'hytale.universe.command.setticking', command: '/setticking' },
    { permission: 'hytale.universe.command.block.inspectphys', command: '/block inspectphys' },
];
export const HYTALE_PERMISSIONS: string[] = HYTALE_PERMISSIONS_DATA.map(p => p.permission);
export const PERMISSION_COMMAND_MAP: Record<string, string> = Object.fromEntries(
    HYTALE_PERMISSIONS_DATA.map(p => [p.permission, p.command])
);
export const getPermissionCategory = (permission: string): string => {
    const parts = permission.split('.');
    if (parts.length >= 2 && parts[0] === 'hytale') {
        return parts[1];
    }
    return 'other';
};
export const getPermissionCategories = (): string[] => {
    const categories = new Set<string>();
    HYTALE_PERMISSIONS.forEach((perm) => {
        categories.add(getPermissionCategory(perm));
    });
    return Array.from(categories).sort();
};
export const getPermissionsByCategory = (): Record<string, string[]> => {
    const byCategory: Record<string, string[]> = {};
    HYTALE_PERMISSIONS.forEach((perm) => {
        const category = getPermissionCategory(perm);
        if (!byCategory[category]) {
            byCategory[category] = [];
        }
        byCategory[category].push(perm);
    });
    return byCategory;
};
export const formatCategoryName = (category: string): string => {
    return category
        .replace(/module$/i, '')
        .replace(/([A-Z])/g, ' $1')
        .trim()
        .split(' ')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join(' ');
};
export const getShortPermissionName = (permission: string): string => {
    const parts = permission.split('.');
    if (parts.length >= 3) {
        return parts.slice(2).join('.');
    }
    return permission;
};
export const getPermissionCommand = (permission: string): string => {
    return PERMISSION_COMMAND_MAP[permission] || permission;
};
